### ISSUE TITLE
Procedures of how to compile and run JEDI

### ISSUE THREAD

**Issue by Neil-untitled** [cap-lab/jedi#10]
Dear cap-lab,

Hope this message finds you well.
I have some problems compiling JEDI.  My platform is NVIDIA XAVIER NX.
What I did is as below:
1. Install all the packages required by tkDNN
2. Install all the prerequisite
3. Go to the terminal
git clone https://github.com/cap-lab/jedi
git clone https://github.com/urmydata/tkDNN.git
cd tkDNN 
mkdir build && cd build
cmake ..
make
 
Error message:
Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00003dc5_00000000-6_normalize.cpp1.ii".
Compilation terminated.
CMake Error at kernels_generated_normalize.cu.o.cmake:280 (message):
  Error generating file
  /home/neo/tkDNN/build/CMakeFiles/kernels.dir/src/kernels/./kernels_generated_normalize.cu.o

CMakeFiles/kernels.dir/build.make:138: recipe for target 'CMakeFiles/kernels.dir/src/kernels/kernels_generated_normalize.cu.o' failed
make[2]: *** [CMakeFiles/kernels.dir/src/kernels/kernels_generated_normalize.cu.o] Error 1
CMakeFiles/Makefile2:182: recipe for target 'CMakeFiles/kernels.dir/all' failed
make[1]: *** [CMakeFiles/kernels.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

I tried to compile tkDNN on Xavier NX but failed to do so.
Could you please teach me how to install tkDNN and jedi properly?

Best 
Neil

**Comment by Neil-untitled** [comment]
I tried to these as well:
git clone https://github.com/cap-lab/jedi
cd jedi
git clone https://github.com/urmydata/tkDNN.git
mkdir build && cd build
cmake ..
make

error message as follows:
[  2%] Linking CXX static library libcuda_kernels.a
[  5%] Built target cuda_kernels
[  8%] Building CXX object src/CMakeFiles/proc.dir/main.cc.o
/home/neo/jedi/src/main.cc:4:10: fatal error: tkDNN/tkdnn.h: No such file or directory
 #include <tkDNN/tkdnn.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/proc.dir/build.make:75: recipe for target 'src/CMakeFiles/proc.dir/main.cc.o' failed
make[2]: *** [src/CMakeFiles/proc.dir/main.cc.o] Error 1
CMakeFiles/Makefile2:127: recipe for target 'src/CMakeFiles/proc.dir/all' failed
make[1]: *** [src/CMakeFiles/proc.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by urmydata** [comment]
Hi,

I think the first message (in tkDNN) is related to this error ([https://github.com/ceccocats/tkDNN/issues/251](https://github.com/ceccocats/tkDNN/issues/251)).
Based on that issue, I think the problem occurs when the TensorRT version is not matched with your board.

Your board' TensorRT version may be higher than the TensorRT 6.
Check the TensorRT version of your board first.
And if your board's TensorRT version is TensorRT8, then please use the '**tensorrt8_experiment**' branch of the forked tkDNN repository (https://github.com/urmydata/tkDNN.git).
In the same way, in the JEDI, please use the '**tensorrt8_support**' branch.

The default version of the forked tkDNN and JEDI is for TensorRT 6, so it is needed to change the branch.
Since TensorRT has been rapidly developed, some old functions in TensorRT are deprecated.
We modified and implemented those repositories to support TensorRT 8, but they are not fully tested as we did with TensorRT 6.
In spite of that, I think this will resolve your problem since we also run the JEDI on the Xavier NX board with the TensorRT 8 in this way.

Also, if the tkDNN is not built, then the JEDI also cannot be built since the JEDI use the tkDNN library.
So, in that sense, the error from the second message occurs since the tkDNN is not built.
In addition, the tkDNN library should be linked in JEDI (the path of the tkDNN library should be specified in the CMake file) when you build the JEDI.

I hope this will be helpful to you.

**Comment by Neil-untitled** [comment]
Thank you very much for replying. I guess that should be able to explain all these errors. I will try to use the TensorRT8 Branch and install. Hope it works. 

All the best

**Comment by Neil-untitled** [comment]
Dear Cap-Lab,

After a lot of trials, I still cannot get Jedi compiled.My versions are as below:
Jetpack 4.6.2
TensorRT: 8.2.1 
cuDNN: 8.2.1
cmake:3.24.0
CUDA:10.2

So I used the tensorrt8_support branch of jedi and tensorrt8_experiment branch of forked tkDNN repo. Here are the details:\

First I clone the tensort8 branch of tkDNN
1. git clone -b tensorrt8_experiment --single-branch https://github.com/urmydata/tkDNN/
2. cd tkDNN && mkdir build && cd build
3. cmake .. && make

This compiles successfully with some warnings about "virtual function override intended?"

Then I cloned the specific tensort8 branch of jedi 
1. git clone -b tensorrt8_support --single-branch https://github.com/cap-lab/jedi.git
   I add "include_directories (/home/neo/tkDNN/ /home/neo/tkDNN/include/ /home/neo/tkDNN/include/tkDNN/ /home/neo/tkDNN/include/tkDNN/pluginsRT/)" in CMakeLists.txt to link jedi with compiled tkDNN
2. cd jedi
3. mkdir build && cd build
4. cmake..
5. make

The build process stopped at 

[ 55%] Linking CXX executable ../bin/proc
/usr/bin/ld: cannot find -ltkDNN
/usr/bin/ld: cannot find -lkernels
collect2: error: ld returned 1 exit status
src/CMakeFiles/proc.dir/build.make:372: recipe for target 'bin/proc' failed
make[2]: *** [bin/proc] Error 1
CMakeFiles/Makefile2:129: recipe for target 'src/CMakeFiles/proc.dir/all' failed
make[1]: *** [src/CMakeFiles/proc.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

This is so confusing to me. Could you please help me?

Best
Neil

**Comment by urmydata** [comment]
That is the link-related error that I mentioned in the last part.
I think you did not specify the path of the built tkDNN library files in CMakeLists.txt.

In the build directory of the tkDNN, there are two library files (_libkernels.so_ and _libtkDNN.so_).
The path of those library files should be specified in CMakeLists.txt file of the JEDI by _link_directories_ keyword of CMake.
For example, _link_directories(your_tkDNN_path/build/)_ (maybe /home/neo/tkDNN/build/)
Header files are also needed to be specified, but you already did.

Or just install by typing 'sudo make install' in the build directory of the tkDNN repository if you have permission.
Then the tkDNN library and header files would be installed in /usr/local/lib and /usr/local/include, respectively.

Also, don't forget other prerequisite dependencies (ex: libconfig++ and libjson-c).
For example, 'sudo apt install libconfig++-dev' and 'sudo apt install libjson-c-dev' to install those libraries.

I hope this will be helpful to you.

**Comment by Neil-untitled** [comment]
Thank you so much! 
As soon as I saw the message I instantly put that link_directories(your_tkDNN_path/build/) into cmakelist
and sudo make install  inside build of tkDNN

Then I started to use "make" in jedi/build again
Here is the error message:
[ 94%] Built target network_analyzer
[ 97%] Building CXX object src/CMakeFiles/compute_coco_map.dir/coco_map.cc.o
In file included from /home/neo/jedi/src/coco_map.cc:9:0:
/usr/include/boost/gil/extension/io/jpeg_io.hpp:29:10: fatal error: jpeglib.h: No such file or directory
 #include <jpeglib.h>
          ^~~~~~~~~~~
compilation terminated.
src/CMakeFiles/compute_coco_map.dir/build.make:75: recipe for target 'src/CMakeFiles/compute_coco_map.dir/coco_map.cc.o' failed
make[2]: *** [src/CMakeFiles/compute_coco_map.dir/coco_map.cc.o] Error 1
CMakeFiles/Makefile2:181: recipe for target 'src/CMakeFiles/compute_coco_map.dir/all' failed
make[1]: *** [src/CMakeFiles/compute_coco_map.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

I am so sorry to keep asking this kind of questions. But it seems like one last step towards successful build.

Best 
Neil

**Comment by urmydata** [comment]
I think that is a prerequisite library.
Could you type the 'sudo apt install libjpeg-dev' to install libjpeg?

Thanks

**Comment by Neil-untitled** [comment]
I am very appreciated for your patience and help. Finally it is successfully built. Thank you very much!
