### ISSUE TITLE
How to estimate the precision of accelerated models?

### ISSUE THREAD

**Issue by Neil-untitled** [cap-lab/jedi#11]
Dear Cap-lab,

Yes, it's me again. Sorry to bother you with this kind of 'silly' question. QAQ

After successfully compiling JEDI and run ./build/bin/proc -c yolov2.cfg ...... I got a result.json file which records the result of detection on COCO val2017 by Yolov2. How can I compute the mean average precision, and AP50? 
I noticed there is a file called  'compute_coco_map' in './build/bin' folder  as well and I guess this could be the right tool to use.
But I don't quite know how to use it. Could you please give me some guidance on using this tool?

Best wishes
Neil

**Comment by urmydata** [comment]
Hello,

As you say, _compute_coco_map_ is a tool to measure mAP.
We are sorry that we forgot to write down how to use the tool.

The usage is below.
```
./build/bin/compute_coco_map <label path file> <yaml file> <result file>
```
- \<label path file> is the file that has the label information which is given in a dataset. If your image path file (which is an _image_path_ in a config file) is /coco2017/all_images.txt, then maybe the label path file is /coco2017/all_labels.txt.
- \<yaml file> is the file provided in tkDNN. You can download it [here](https://github.com/urmydata/tkDNN/blob/master/demo/config.yaml).
- \<result file> is the results.json file.

We hope this will be helpful to you.

Thanks

**Comment by Neil-untitled** [comment]
Thank you so much for replying.

Regarding _label path file_, I download val2017 using '_setting.sh_'
_wget http://images.cocodataset.org/zips/val2017.zip
unzip val2017.zip_

There is no such file like 'all_labels.txt' inside. So I managed to use a tool in _tkDNN/scripts/download_validation.sh_ folder by
_bash ./tkDNN/scripts/download_validation.sh COCO_
This command downloads COCO_val2017 from a link and unzip the file into two folders and two txt files.
Here we go then there are _images, labels_ folder and _all_images.txt, all_labels.txt_
After I configured the relevant paths in yolov2.cfg file (which is  ./data/COCO_val2017/all_images.txt), I tried to run ._/build/bin/proc_ again, however, this time, inside _result.json_, all the _image_id_ s became 0. It is like
' _{"image_id":0, category......}_ for every line.

I didn't notice this until I ran 
./build/bin/compute_coco_map ./data/COCO_val2017/all_labels.txt  ./tkDNN/demo/config.yaml  result_v4tiny.json
The output is like:
Classes: 80 mAP 0.5: 0
Classes: 80 mAP 0.55: 0
......... all zeroes because image_ids don't match I guess.

The weird thing is, if I change the _image_path_ and _calibration_path_ in cfg file back to ./data/val2017/all_images.txt, all the image_ids go back to normal as they should look like.
Are there any inherent differences between the folder _val2017_ (downloaded by commands in _setting.sh_)and folder _COCO_val2017_ which I downloaded using _scripts/download_validation.sh_? I am so confused(facepalm). One important fact I discovered is: if I exchange the folder names of these two folders, image id appear again in the result.json using whichever folder that has the name 'val2017'.

All the best
Neil

**Comment by Neil-untitled** [comment]
Follow the last post, 

I changed the name of ./data/COCO_val2017 to ./data/val2017, all image_id s come back! Good news but I still don't understand what's going on (facepalm)

Then I ran ./build/bin/compute_coco_map ./data/all_labels.txt  ./tkDNN/demo/config.yaml  resultv2.json (somehow all_labels.txt has to be in exactly the subdir of data, it can't be data/val2017/all_labels.txt or deeper.)
The mAP result is much lower than I expected. (I tried yolov4 tiny as well, almost the same result), as below:
Classes: 80 mAP 0.5: 0.000123762
Classes: 80 mAP 0.55: 0.000123762
Classes: 80 mAP 0.6: 0.000123762
Classes: 80 mAP 0.65: 0.000123762
Classes: 80 mAP 0.7: 0.000123762
Classes: 80 mAP 0.75: 0.000123762
Classes: 80 mAP 0.8:  0
Classes: 80 mAP 0.85: 0
Classes: 80 mAP 0.9: 0
Classes: 80 mAP 0.95: 0
mAP 0.5:0.95 = 7.42574e-05
avg precision: 0.003125  avg recall: 6.57895e-05   avg f1 score:0.000128866

I guess one possible reason for this is that the model loaded into the TensorRT engine is not pretrained?
Is that the actual explanation? Hope to get some help. Thanks in advance!

Best wishes
Neil

**Comment by urmydata** [comment]
Hi, 

We confirmed by reproducing the error as you said. We noticed that your downloaded image file contains 5,000 image paths while the label file only has 4,952 label paths. The previous version of _compute_coco_map_ worked when the number and order of items in the label and image list files are exactly same.

To fix this issue, we updated the _compute_coco_map_, and you can get an updated code by 'git pull' command in the _tensorrt8_support_ branch of the jedi repository. We tested with 5,000-image path file and 4,952-label path file and works OK with the updated version.

Thanks

**Comment by Neil-untitled** [comment]
Thank you very much for all the help. Problem solved perfectly! Have a nice day.

Best wishes
Neil
